// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  UAS2030ID: [
    "UAS2030/wolcome",
    "UAS2030/main-rules",

    {
      type: 'category',
      label: 'Resources',
      items: [
        
        {type: 'category',
         label: 'AI/Vision',
        items:['UAS2030/test']},
        
        {type: 'category',
          label: 'Flight Control',
         items:['UAS2030/test']},

         {type: 'category',
          label: 'Communication',
         items:['UAS2030/test']},
      

         {type: 'category',
          label: 'Airframe & Payload',
         items:['UAS2030/test']},
      

         {type: 'category',
          label: 'Media',
         items:['UAS2030/test']},
      

         {type: 'category',
          label: 'Logistics',
         items:['UAS2030/test']},



      
      
      
      
      ],
    },
    "UAS2030/drone",


  ],


  ROSID: [
    "ROS/Prerequisites",
    "ROS/resources",
  ],


  DepartmentID: [
    "AE-Department/test",
  ],


  IRCID: [
    "AE-IRC/test",
  ],


// 'tutorial-basics/create-a-document'



};

export default sidebars;
